spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chinook
    username: student
    password: 123
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
